// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // The generated client emits explicit .js specifiers, which ts-node cannot
    // map back to its .ts sources. Compiling first sidesteps the mismatch.
    seed: "npm run seed:run",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
